[tool.poetry]
name = "tetris-battleroyale"
version = "0.1.0"
description = ""
authors = ["Lorenzo Rigoni <lorenzo.rigoni2@studio.unibo.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
